# # # with data.table--------------------------
#
# library(data.table)
# df <-as.data.table(df_raw[-(1:2),1:2])
# colnames(df) <- c("Date", "RealizedVariance")
#
# # add mean per week and per month for data.table
# as.Date(as.character(df$Date), "%Y%m%d")
# df$Date <- as.Date(as.character(df$Date), "%Y%m%d")
# df <- df %>% group_by (yw = paste(year(Date), week(Date), sep = "-"))
# df <- df %>% group_by( ym = paste(year(Date), month(Date), sep = "-"))
#
# # # with factor instead of numeric --------------------------
#
# # add realized variance on weekly and monthly basis: average over respective period
# # weekly
# mean(as.numeric(levels(df2$RealizedVariance[1:5])[df2$RealizedVariance[1:5]]),na.rm=T) # mean of first week
#
# Vol$WeeklyVariance <- ave(as.numeric(levels(Vol$RealizedVariance)[Vol$RealizedVariance]), Vol$yw, FUN=function(x) mean(x, na.rm=T)) # add weekly average
# Vol$MonthlyVariance <- ave(as.numeric(levels(Vol$RealizedVariance)[Vol$RealizedVariance]), Vol$ym, FUN=function(x) mean(x, na.rm=T)) # add monthly average
#
# weekly_var <- vector()
# n <- 1
# while(n<length(df2$RealizedVariance)) {
#   weekly_var <- c(weekly_var,mean(as.numeric(levels(df2$RealizedVariance[n:(n+4)])[df2$RealizedVariance[n:(n+4)]]),na.rm=T))
#   n<-n+5
# }
# rm(n)
#
# # monthly
# monthly_var <- vector()
# n <- 1
# while(n<length(df2$RealizedVariance)) {
#   weekly_var <- c(weekly_var,mean(as.numeric(levels(df2$RealizedVariance[n:(n+4)])[df2$RealizedVariance[n:(n+4)]]),na.rm=T))
#   n<-n+5
# }
# rm(n)
#
# # # monthly and weekly averages (non-moving) (first part belongs to creation of dataset, second to graphics) -------------

# Vol <- Vol %>% group_by (yw = paste(year(Date), week(Date), sep = "")) # add unique week index (temp)
# Vol <- Vol %>% group_by(ym = paste(year(Date), month(Date), sep = "")) # add unique month index (temp)
# Vol$yw <- as.numeric(Vol$yw) # turn the unique week index in numeric
# Vol$ym <- as.numeric(Vol$ym) # turn the unique month index in numeric
# Vol$WeeklyVariance <- ave(Vol$RealizedVariance, Vol$yw, FUN=function(x) mean (x,na.rm = T)) # create weekly average
# Vol$MonthlyVariance <- ave(Vol$RealizedVariance, Vol$ym, FUN=function(x) mean (x,na.rm = T)) # create monthly average
# Vol <- Vol[,-(3:4)] # remove week and month index
#
# plot(Df$WeeklyVariance, grid.col = NA, main = "Weekly Realized Variance")
# plot(Df$MonthlyVariance, grid.col = NA, main = "Monthly Realized Variance")



# # # try to find a way to plot my data in a good way (shorter y axis) ------------------------------------------

# with ggfortify
plot_data2 <- function(variable, title, save_name) {
  plot <- ggfortify:::autoplot.ts(variable) + theme_classic()
  return(plot)
}

# with plotly
plot_data3 <- function(variable, title, save_name) {
  plot <- plotly::ggplotly(variable)
  return(plot)
}


# with ggplot
zoo:::autoplot.zoo(Df$RealizedVariance, geom = "line") + coord_fixed(ratio = 10)

class(fortify.zoo(Df$RealizedVariance))


ggplot(data = Df$RealizedVariance, aes(Index, RealizedVariance))  + geom_path()

autoplot(Df$RealizedVariance, geom = "line")

## use either autoplot by zoo, or fortify.zoo which turns the object into a data frame!

## how do I get both in one?

## how do I cut high observations away?

## does it make sense to make a log graph?

# # # old regressions---------------------------------

# idea was one last table combining both squared and not squared model, but it is not yet build as I am not sure it is a good idea

regress_data_all <- function(df, outfile) {
 lm1 <- lm(Hmisc::Lag(Df$RealizedVariance, shift=-1) ~ Df$RealizedVariance + Df$RealizedVariance %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% rollapply(20,mean,na.rm = T))
 lm2 <- lm(Hmisc::Lag(Df$RealizedVariance, shift=-1) ~ Df$RealizedVariance + Df$RealizedVariance %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% rollapply(20,mean,na.rm = T) + Df$VIX.Close)
 lm3 <- lm(Df$RealizedVariance %>% sqrt () %>% Hmisc::Lag(shift=-1) ~ Df$RealizedVariance %>% sqrt() + Df$RealizedVariance %>% sqrt() %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% sqrt() %>% rollapply(20,mean,na.rm = T))
 lm4 <- lm(Df$RealizedVariance %>% sqrt () %>% Hmisc::Lag(shift=-1) ~ Df$RealizedVariance %>% sqrt() + Df$RealizedVariance %>% sqrt() %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% sqrt() %>% rollapply(20,mean,na.rm = T) + Df$ VIX.Close %>% sqrt())
}

## old single regressions

#' regression like HAR-RV model
#'
#' @param x a dataset generated by build_dataset
#' @param outfile the path to a file where the regression is saved to (specity outputfile type, e.g. ".tex")
#'
#' @return NULL
#' @export
#'
#' @examples
#' Df <- mtcars
#' regerss_data1(Df, "example.tex")
regress_data_har <- function(x,outfile) {
  lm1 <- lm(Hmisc::Lag(Df$RealizedVariance, shift=-1) ~ Df$RealizedVariance + Df$RealizedVariance %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% rollapply(20,mean,na.rm = T))
  texreg::texreg(lm1, file = outfile, custom.coef.names=c("Intercept", "$RV_{t}^{d}$", "$RV_{t}^{w}$", "$RV_{t}^{m}$"))
}

#' regression like HAR-RV model plus VIX
#'
#' @param x a dataset generated by build_dataset
#' @param outfile the path to a file where the regression is saved to (specity outputfile type, e.g. ".tex")
#'
#' @return
#' @export
#'
#' @examples
#' Df <- mtcars
#' regress_data(Df, "example.tex")
#'
regress_data_vix <- function(x,outfile) {
  lm2 <- lm(Hmisc::Lag(Df$RealizedVariance, shift=-1) ~ Df$RealizedVariance + Df$RealizedVariance %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% rollapply(20,mean,na.rm = T) + Df$VIX.Close)
  texreg::texreg(lm2, file = outfile, custom.coef.names=c("Intercept", "$RV_{t}^{d}$", "$RV_{t}^{w}$", "$RV_{t}^{m}$","VIX"))
}

## old together regressions

#' 2 regressions, (1) HAR-RV alone with RV = volatility (unsquared returns) and (2) 1 with VIX (unsquared)
#'
#' @param Df a dataset generated by build_dataset
#' @param outfile the path to a file where the regressions are saved to (specity outputfile type, e.g. ".tex")
#'
#' @return
#' @export
#'
#' @examples
#' regress_data(Df, "example.tex")
#'
regress_data_harvix <- function(Df, outfile) {
  lm1 <- lm(Hmisc::Lag(Df$RealizedVariance, shift=-1) ~ Df$RealizedVariance + Df$RealizedVariance %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% rollapply(20,mean,na.rm = T))
  lm2 <- lm(Hmisc::Lag(Df$RealizedVariance, shift=-1) ~ Df$RealizedVariance + Df$RealizedVariance %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% rollapply(20,mean,na.rm = T) + Df$VIX.Close)
  texreg::texreg(l=list(lm1,lm2), file = outfile, custom.model.names = c("HAR-RV","HAR-RV with VIX"), custom.coef.names=c("Intercept", "$RV_{t}^{d}$", "$RV_{t}^{w}$", "$RV_{t}^{m}$","VIX"), table = FALSE)
}


#' 2 regressions, (1) HAR-RV alone with RV = volatility (unsquared returns) and (2) 1 with VIX (unsquared)
#'
#' @param df a dataset generated by build_dataset
#' @param outfile the path to a file where the regressions are saved to (specity outputfile type, e.g. ".tex")
#'
#' @return
#' @export
#'
#' @examples
#' regress_data(Df, "example.tex")
#'
regress_data_harvixln <- function(df, outfile) {
  lm3 <- lm(Df$RealizedVariance %>% log() %>% Hmisc::Lag(shift=-1) ~ Df$RealizedVariance %>% log() + Df$RealizedVariance %>% log() %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% log() %>% rollapply(20,mean,na.rm = T))
  lm4 <- lm(Df$RealizedVariance %>% log() %>% Hmisc::Lag(shift=-1) ~ Df$RealizedVariance %>% log() + Df$RealizedVariance %>% log() %>% rollapply(5,mean,na.rm = T) + Df$RealizedVariance %>% log() %>% rollapply(20,mean,na.rm = T) + Df$VIX.Close %>% log())
  texreg::texreg(l=list(lm3,lm4), file = outfile, custom.model.names = c("HAR-RV","HAR-RV with VIX"), custom.coef.names=c("Intercept", "$RV_{t}^{d}$", "$RV_{t}^{w}$", "$RV_{t}^{m}$","VIX"), table = FALSE)
}

# # # testing the lag -----------------------------------
##-> careful, lag vs. Lag (Hmisc)

# rollapply uses the same day (2000-01-07 shows average of 2000-01-07 inclusive)
test <- Df$RealizedVariance %>% rollapply(width=5,mean,na.rm = T) %>% lag(1)
test[(1:20),]
Df$RealizedVariance[(1:5),] %>% sum()/5

# lag in xts shifts each observation one time period ahead, so on 2000-01-04 the observation of 2000-01-03 is shown -> lag(RV,1) = RV(t-1)
# lag(1) is equivalent to Hmisc::Lag(shift = 1)
# to shift to RV(t+1) we need the Hmisc::Lag (shift = -1)
Lag_var <- Hmisc::Lag(Df$RealizedVariance, shift = 1)
Lead_var <- Hmisc::Lag(Df$RealizedVariance, shift = -1)
Df$RealizedVariance[1:5,]
head(Lag_var)
head(Lead_var)


plot_data2(Df$RealizedVariance, Df$VIX.Close, "RV and VIX", "test.png")
autoplot(Df$RealizedVariance, Df$VIX.Close)
autoplot(Df$RealizedVariance)





head(Df)
head(Df_frame)

ggplot(data = Df_frame, aes(x = Date, y = RealizedVariance)) + geom_line(color = "#00AFBB", size = 1) +
  theme_minimal()

ggplot(data = Df_frame, aes(x=Date, y = VIX.Close)) + geom_line(color = "#00AFBB", size = 1) +
  theme_minimal()

ggplot(data = Df_frame, aes(x=Date, y = SP500)) + geom_line(color = "#00AFBB", size = 1) +
  theme_minimal()


ggplot(Df_frame, aes(x = Date)) +
  geom_line(aes(y = RealizedVariance, color = "Realized Variance"), size = 1) + ## realized variance in blue
  geom_line(aes(y = VIX.Close/1000,  color = "VIX (Close)"), size  = 1) +  ## vix in orange
  scale_y_continuous(sec.axis = sec_axis(~.*1000, name = "VIX")) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  labs(y = "Realized Variance", color = "Legend") +
  theme(legend.position = c(0.8, 0.9))


ggplot(Df_frame, aes(x = Date)) +
  geom_line(aes(y = VIX.Close,  color = "VIX (Close)"), size  = 1) +  ## vix in orange
  geom_line(aes(y = SP500/20, color = "SP500"), size = 1) + ## SP500 in blue
  scale_y_continuous(sec.axis = sec_axis(~.*20, name = "S&P 500", breaks = c(400,800,1200,1600,2000)), breaks = c(20,40,60,80,100)) +
  scale_x_date(breaks = "2 years", date_labels = "%Y") +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  labs(y = "VIX (Close)", x = "Year", color = "Legend") +
  theme(legend.position = c(0.8,0.9), panel.grid.major = element_line(colour = "grey92"), panel.grid.minor = element_line(colour = "grey92"),
        text = element_text(size = 20), axis.text = element_text(size = 14))


