#' 2 regressions, (1) RV(t) on RV(d,t-1) + RV(w,t-1) + RV(m,t-1) and (2) same with + VIX(t)
#'
#' @param Df a dataset generated by build_dataset
#' @param outfile the path to a file where the regressions are saved to (specity outputfile type, e.g. ".tex")
#'
#' @return
#' @export
#'
#' @examples
#' regress_data(Df, "example.tex")
#'
Regress_data_harvix <- function(Df, outfile) {
  lm1 <- lm(Df$RealizedVolatility ~ Df$RealizedVolatility %>% lag(1) + Df$RealizedVolatility %>% rollapply(5,mean,na.rm = T) %>% lag(1) + Df$RealizedVolatility %>% rollapply(22,mean,na.rm = T) %>% lag(1))
  lm2 <- lm(Df$RealizedVolatility ~ Df$RealizedVolatility %>% lag(1) + Df$RealizedVolatility %>% rollapply(5,mean,na.rm = T) %>% lag(1) + Df$RealizedVolatility %>% rollapply(22,mean,na.rm = T) %>% lag(1) + Df$VIX.Close)
  Regressions <- list(lm1, lm2)
  print(Regressions)
  texreg::texreg(l=list(lm1,lm2), file = outfile, custom.model.names = c("Historic","Historic and VIX"), custom.coef.names=c("Intercept", "$RV_{t}^{d}$", "$RV_{t}^{w}$", "$RV_{t}^{m}$","VIX"), table = FALSE)
}
